Création interface pour ladders
noobgamecontest/versus pull request #9
Opened 2020-11-16 14:01 UTC by leguy-design

2020-11-16 21:55 UTC, Ykmar requested changes

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/LadderController.php
> +    public function update(Ladder $ladder, UpdateLadderFormRequest $request)
retour typage, est ce que tu vois l'intérêt de typer ton retour ?

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/LadderController.php
> +    public function destroy(Ladder $ladder)
typage retour

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/TeamController.php
> +    public function store(Request $request)
retour typage

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/LadderController.php
>          ]);
Tu fais un form request pour l'update mais pas pour le create, est ce qu'il y a une raison ?

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/TeamController.php
> +        return Redirect::route('teams.index');
idem pourquoi un form request pour l'un et pas pour l'autre ?

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Front/LadderController.php
> +        dd($ladder);
Han un dd() ... XD

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Front/LadderController.php
> +        return response()->view('ladder.teams', ['teams' => $teams]);
Je crois que ça, ça marche pas, ta variable $teams n'est pas instancié

Et au passage le nom teams() n'est pas très explicite, si tu veux faire une méthode qui te renvoie des équipe, appelle la getTeams(), c'est pas grand chose mais ça permet plus de clarté

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Controllers/Ajax/LadderController.php
> -        return response()->json($ladder);
si on fait de l'ajax, on doit faire un retour en json

2020-11-16 21:55 UTC, Ykmar commented on app/Http/Requests/UpdateLadderFormRequest.php
> +class UpdateLadderFormRequest extends FormRequest
Vu que ton form request va être appliqué sur une route en ajax, il va falloir faire un petit tricks dans cette classe pour que ça fonctionne, je te laisse chercher ;)

2020-11-16 21:55 UTC, Ykmar commented on app/Models/Team.php
> +
Alors ça c'est trop mignon XD

La méthode where est inné aux model Eloquent

2020-11-16 21:55 UTC, Ykmar commented on app/Models/Team.php
> +    public function ladders():BelongsToMany
espace entre deux point et le type

2020-11-16 21:55 UTC, Ykmar commented on composer.lock
> -{
au passage le composer.lock ne doit pas être commit

2020-11-16 21:55 UTC, Ykmar commented on database/migrations/2020_09_14_112944_create_ladders_table.php
> +            });
tabulation en trop

2020-11-16 21:55 UTC, Ykmar commented on routes/web.php
> +
du coup ça a été supprimé avant la PR ? XD

2020-11-16 21:56 UTC, william-suppo requested changes

2020-11-16 21:56 UTC, william-suppo commented on app/Http/Controllers/Front/TeamController.php
> +<?php
C'est pas l'objet de la feature ;)

2020-11-16 21:56 UTC, william-suppo commented on app/Http/Controllers/Ajax/LadderController.php
> +    public function store(Request $request): RedirectResponse
Une api retourne du json.

2020-11-16 21:56 UTC, william-suppo commented on app/Http/Controllers/Front/LadderController.php
> +        dd($ladder);
Il est où dd ?

2020-11-16 21:56 UTC, william-suppo commented on app/Http/Controllers/Front/LadderController.php
> +        $teams = Team::all();
Il me semble que cette interface existe déjà.

2020-11-16 21:56 UTC, william-suppo commented on app/Http/Requests/UpdateLadderFormRequest.php
> +<?php
C'est cool ça ;)

2020-11-16 21:56 UTC, william-suppo commented on app/Models/Ladder.php
> +        'name', 'description','image_url', 'category'
Il manque un espace.

2020-11-16 21:56 UTC, william-suppo commented on app/Models/Team.php
> +        'name', 'elo', 'level', 'avatar', 'ladder_id',
là il y a l'espace

2020-11-16 21:56 UTC, william-suppo commented on app/Models/Team.php
> +    public static function where($string, $id)
where you go ?

2020-11-16 21:56 UTC, william-suppo commented on database/migrations/2020_09_14_112944_create_ladders_table.php
> +
Et c'est la ligne fantôme !

2020-11-16 21:56 UTC, william-suppo commented on database/migrations/2020_09_14_112944_create_ladders_table.php
> +            });
Tab tab tab

2020-11-16 21:56 UTC, william-suppo commented on resources/css/app.css
> +
Comment ces modifs sont arrivés ?

2020-11-16 22:01 UTC, meinder-a commented
<img src="https://cdn.shopify.com/s/files/1/0061/6765/8585/products/biafine_800x.jpg?v=1571762153">

2020-11-16 22:35 UTC, TomAuzuret commented on resources/js/components/Ladders/LadderRankingComponent.vue
> +        console.log(this.teams);
bha bravo

2020-11-16 22:35 UTC, TomAuzuret commented on resources/js/components/Ladders/LadderRankingComponent.vue
> -            axios.get('/ajax/ladders/' + this.ladder.id + '/ranking').then(response => {
/ajax/ladders/${this.ladder.id}ranking

Ca doit etre entouré de backtick pour être interprété
Plus beau je trouve

2020-11-16 22:35 UTC, TomAuzuret commented on resources/js/components/Ladders/LaddersComponent.vue
> +            <div v-on:click="showRanking(ladder)"  class="px-6 py-4 hover:shadow-lg bg-blue-500 border-b-2 border-t border-l border-r border-black mb-4">
Tu peux passer une props via ton blade et genre 

<composant redirect= {{route('nomdelaroute') }} /> 

ca peut eviter :  window.location.href = 'ladders/' + ladder.id + '/ranking';

2020-11-16 22:35 UTC, TomAuzuret commented on resources/js/components/Ladders/LadderEditComponent.vue
> +        props: ['ladder'],
Type les

2020-11-17 08:55 UTC, leguy-design commented on app/Http/Controllers/Ajax/LadderController.php
> +    public function update(Ladder $ladder, UpdateLadderFormRequest $request)
maintenant oui !

2020-11-17 08:57 UTC, leguy-design commented on app/Http/Controllers/Ajax/LadderController.php
>          ]);
oops non je vais corriger ça

2020-11-17 09:02 UTC, leguy-design commented on app/Models/Team.php
> +
c'est l'ide de laravel qui me l'a conseillé quand j'ai rencontré des soucis sur mon controller :@ j'ai oublié de supprimer

2020-11-17 09:06 UTC, leguy-design commented on composer.lock
> -{
j'ai push une deuxième fois dans la journée sans le composer.lock et le package-lock.json

2020-11-17 09:13 UTC, leguy-design commented on routes/web.php
> +
ptdr on va dire que oui :'(

2020-11-17 09:17 UTC, leguy-design commented on app/Http/Controllers/Ajax/LadderController.php
> +    public function store(Request $request): RedirectResponse
j'comprend meme pas pourquoi j'ai touché à ta function ranking sorry ^^'

2020-11-17 09:18 UTC, leguy-design commented on app/Http/Controllers/Front/LadderController.php
> +        dd($ladder);
crotte de bik ça devait etre supprimé tout ça :'(

2020-11-17 09:23 UTC, leguy-design commented on app/Http/Controllers/Front/LadderController.php
> +        $teams = Team::all();
oui ! j'ai joué avec ton code et j'ai pas rangé correctement après avoir fini :@

2020-11-17 09:27 UTC, leguy-design commented on app/Models/Team.php
> +    public static function where($string, $id)
oh nnnn pas encore :'(
"c'est l'ide de laravel qui me l'a conseillé quand j'ai rencontré des soucis sur mon controller :@ j'ai oublié de supprimer"

2020-11-17 09:27 UTC, leguy-design commented on database/migrations/2020_09_14_112944_create_ladders_table.php
> +
bouh

2020-11-17 09:31 UTC, leguy-design commented on resources/css/app.css
> +
je pensais que je devais y ajouter un peu de style :'(

2020-11-17 09:33 UTC, leguy-design commented on resources/js/components/Ladders/LadderRankingComponent.vue
> +        console.log(this.teams);
enchanté

2020-11-17 09:40 UTC, leguy-design commented on resources/js/components/Ladders/LaddersComponent.vue
> +            <div v-on:click="showRanking(ladder)"  class="px-6 py-4 hover:shadow-lg bg-blue-500 border-b-2 border-t border-l border-r border-black mb-4">
grave cool !!!!!!!!!!

2020-11-17 09:43 UTC, leguy-design commented on resources/js/components/Ladders/LadderEditComponent.vue
> +        props: ['ladder'],
merci du tips

2020-11-17 09:48 UTC, leguy-design commented
**MERCI BEAUCOUP POUR TOUT VOS COMMENTAIRES !!!!**

2020-11-17 11:10 UTC, leguy-design commented on app/Http/Controllers/Front/TeamController.php
> +<?php
joker

2020-11-17 11:29 UTC, william-suppo commented on resources/css/app.css
> +
Pas de problème, juste savoir comment tu as procéder ;)

2020-11-18 08:15 UTC, william-suppo requested changes
Pourquoi je te dis que la gestion des teams n'est pas l'objet ?

Essentiellement pour produire des petites features digestes pour tous : Le dev, le relecteur, le responsable d'application.

Comme ça, on peut la merge rapidement et sans danger.

2020-11-18 08:15 UTC, william-suppo commented on app/Http/Controllers/Ajax/TeamController.php
Nope, c'est pas la feature monsieur ;)

2020-11-18 08:15 UTC, william-suppo commented on app/Http/Requests/StoreTeamFormRequest.php
> +<?php
C'est pas l'objet !

2020-11-18 08:16 UTC, william-suppo commented
Est-ce que tu peux nous mettre des screenshots plz ;)

2020-11-18 10:21 UTC, leguy-design commented
**INTERFACE LADDER -> INDEX**
![Capture d’écran de 2020-11-18 10-00-30](https://user-images.githubusercontent.com/62065918/99517671-eee55080-298f-11eb-9410-be779bb8c9a6.png)

**INTERFACE LADDER -> CREATE**
![Capture d’écran de 2020-11-18 10-01-03](https://user-images.githubusercontent.com/62065918/99517773-0c1a1f00-2990-11eb-90d4-b98bcabb75c9.png)


**INTERFACE LADDER -> EDIT**
![Capture d’écran de 2020-11-18 10-01-33](https://user-images.githubusercontent.com/62065918/99517857-22c07600-2990-11eb-9a4e-9b60bb8f9367.png)

2020-11-19 17:23 UTC, leguy-design commented
![Capture d’écran de 2020-11-19 18-21-46](https://user-images.githubusercontent.com/62065918/99700989-2c330680-2a94-11eb-978f-a301c149d7db.png)
![Capture d’écran de 2020-11-19 18-20-13](https://user-images.githubusercontent.com/62065918/99700997-2fc68d80-2a94-11eb-9001-01d0006acc8b.png)
![Capture d’écran de 2020-11-19 18-19-15](https://user-images.githubusercontent.com/62065918/99701011-33f2ab00-2a94-11eb-834c-f06ceb76f9d8.png)
![Capture d’écran de 2020-11-19 18-20-23](https://user-images.githubusercontent.com/62065918/99701021-36550500-2a94-11eb-949d-9491ed09504d.png)
![Capture d’écran de 2020-11-19 18-19-24](https://user-images.githubusercontent.com/62065918/99701056-410f9a00-2a94-11eb-8e90-61877bb24752.png)
![Capture d’écran de 2020-11-19 18-19-19](https://user-images.githubusercontent.com/62065918/99701071-44a32100-2a94-11eb-95b1-70fb8b8aca8f.png)

2020-11-19 22:40 UTC, TomAuzuret requested changes

2020-11-19 22:40 UTC, TomAuzuret commented on resources/views/ladder/index.blade.php
> +            @endif
Je préfère faire ca aussi au cas ou 

```
  @if (auth()->user()->role == 'admin')
                <a href="{{ route('ladder.create') }}" class="mt-1 md:mt-11 hover:underline mx-auto absolute text-gray-900 font-bold text-sm lg:text-2xl">Nouveau ladder</a>
            @elseif($maybeTrue)
            @elseif($maybeFalse)
           @elseif($maybeNull)
            @endif
```

Comem ac tu as tout les cas

2020-11-19 22:47 UTC, Ykmar commented
Dans Ajax/LadderController, renomme ta méthode index() en getAll(), index fait très souvent référence à une vue, or là on renvoie une collection de Ladder donc un getAll semble approprié et, on précise le All parce que on pourrait aussi avoir une méthode get() qui renverrait un seul Ladder ;)

2020-11-19 22:49 UTC, Ykmar commented on app/Http/Controllers/Front/LadderController.php
> +    public function create()
typage

2020-12-06 23:26 UTC, closed without merging